#define VID_Counter 80
#define VID_DestoryTarget 10
#define VID_DisableTarget 11
#define VID_DisarmTarget 12
#define VID_DestroySubsys 13
#define VID_ProtectTarget 14
#define VID_IgnoreTarget 15
#define VID_FormWing 16
#define VID_CoverMe 17
#define VID_EngageEnemy 18
#define VID_Depart 19
#define VID_Action 250
#define VID_WingName 251
#define VID_TopMenu 252
#define VID_ShipName 253
#define VID_Number 254
#define VID_Ships 50
#define VID_Wings 51
#define VID_AllFighters 52
#define VID_AllWings 53
#define VID_Reinforcements 54
#define VID_SupportShip 55
#define VID_AbortSupport 56
#define VID_Cancel 57
#define VID_Command 58
#define VID_More 59
