//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Launcher.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LAUNCHER_DIALOG             102
#define IDS_1ST_TAB                     102
#define IDS_2ND_TAB                     103
#define IDS_3RD_TAB                     104
#define IDS_4TH_TAB                     105
#define IDS_5TH_TAB                     106
#define IDS_6TH_TAB                     107
#define IDS_7TH_TAB                     108
#define IDS_8TH_TAB                     109
#define IDS_STRING_FS2_FORUM            121
#define IDS_STRING_RT_HOME              122
#define IDR_MAINFRAME                   128
#define IDD_REG_OPTIONS                 131
#define IDD_VIDEO                       133
#define IDD_NETWORK                     134
#define IDD_JOYSTICK                    135
#define IDD_SOUND                       135
#define IDD_DX8                         136
#define IDD_OGL                         138
#define IDD_DX5                         141
#define IDD_3DFX                        142
#define IDD_SPEECH                      143
#define IDD_BUGS                        145
#define IDD_HELP                        146
#define IDD_DX9                         147
#define IDB_TITLE2                      150
#define IDB_TITLE3                      151
#define IDD_DIALOG1                     152
#define IDD_MOD                         152
#define IDD_COMM_LINE                   153
#define IDB_TITLE                       154
#define IDC_BUTTON1                     1001
#define IDC_BROWSE                      1001
#define IDC_SET                         1001
#define IDC_CALIBRATE                   1001
#define IDC_GEN_CAPS                    1001
#define IDC_PLAY                        1001
#define IDC_SELECT_MOD                  1001
#define IDC_TEST_PSHADER                1001
#define IDC_REPORT_BUG                  1001
#define IDC_SETTINGS_MOD                1001
#define IDC_DETECT_JOYSTICK             1002
#define IDC_COMM_LINE_PATH              1003
#define IDC_GEN_CAPSB                   1003
#define IDC_CHECK1                      1004
#define IDC_FORCE_FREEDBACK             1004
#define IDC_HI_SPARKY_CHECKBOX          1004
#define IDC_GF4_FIX                     1004
#define IDC_SPEECH_INGAME               1004
#define IDC_ALLOW_NON_SMODES            1004
#define IDC_USE_FLAGS_CHECK             1004
#define IDC_CHECK2                      1005
#define IDC_DIR_HIT                     1005
#define IDC_LTXT_CHECKBOX               1005
#define IDC_SPEECH_TECHROOM             1005
#define IDC_FLAG_HELP                   1005
#define IDC_CHECK3                      1006
#define IDC_SPEECH_BRIEFINGS            1006
#define IDC_GF4_FFIX                    1006
#define IDC_CHECK4                      1007
#define IDC_CHECK5                      1008
#define IDC_CHECK6                      1009
#define IDC_CHECK7                      1010
#define IDC_CHECK8                      1011
#define IDC_CHECK9                      1012
#define IDC_CHECK10                     1013
#define IDC_EDIT2                       1014
#define IDC_PATH                        1014
#define IDC_ERROR                       1014
#define IDC_CUSTOM_IP                   1014
#define IDC_APPLY                       1015
#define IDC_HOLDER                      1016
#define IDC_DLG_HOLDER                  1017
#define IDC_LIST3                       1023
#define IDC_REG_LIST                    1023
#define IDC_REG_LOCATION                1024
#define IDC_RUN                         1025
#define IDC_CUSTOM_PARAM                1027
#define IDC_EXE_TYPE                    1028
#define IDC_FLAG_LIST                   1029
#define IDC_NEW_VALUE                   1035
#define IDC_GFXAPI_LIST                 1037
#define IDC_CDEPTH_LIST                 1038
#define IDC_RES_LIST                    1039
#define IDC_ANTIALIAS_LIST              1040
#define IDC_SETTINGS_LIST               1041
#define IDC_ADAPTER_LIST                1041
#define IDC_NET_TYPE_1                  1042
#define IDC_NET_TYPE_2                  1043
#define IDC_NET_TYPE_3                  1044
#define IDC_CONSPEED_1                  1045
#define IDC_CONSPEED_2                  1046
#define IDC_CONSPEED_3                  1047
#define IDC_CONSPEED_4                  1048
#define IDC_CONSPEED_5                  1049
#define IDC_CONSPEED_6                  1050
#define IDC_LOCAL_PORT                  1051
#define IDC_API_HOLDER                  1052
#define IDC_OGL_RES                     1056
#define IDC_SOUND_CARD                  1057
#define IDC_DX5_RES                     1058
#define IDC_GLIDE_RES                   1059
#define IDC_DX8_NOT_INSTALLED           1060
#define IDC_EDIT                        1062
#define IDC_VOLUME_SLIDER               1063
#define IDC_NO_MOD                      1065
#define IDC_MOD_NAME                    1066
#define IDC_RT_HOME                     1073
#define IDC_FS2_FORUM                   1074
#define IDC_DEV_TOOLS                   1074
#define IDC_PSHADER_V                   1075
#define IDC_VSHADER_V                   1076
#define IDC_SOURCE                      1076
#define IDC_BUGS                        1077
#define IDC_VOICE_COMBO                 1079
#define IDC_BUTTON3                     1081
#define IDC_GAME_README                 1081
#define IDC_GET_TXT_SIZE                1081
#define IDC_MOD_FORUM                   1081
#define IDC_BUTTON2                     1082
#define IDC_GET_VOICES                  1082
#define IDC_TEST_DXT                    1082
#define IDC_MOD_WEBSITE                 1082
#define IDC_SETTINGS_NORMAL             1082
#define IDC_REGISTER_BUTTON             1082
#define IDC_JOYSTICK                    1083
#define IDC_GOTO_FORUM                  1084
#define IDC_FLAG_SETUP                  1086
#define IDC_SPIN1                       1087
#define IDC_FLAG_TYPE                   1087
#define IDC_FEATURES_ON                 1088
#define IDC_FEATURES_OFF                1089
#define IDC_CUSTOM                      1090
#define IDC_LOGO1                       1091
#define IDB_TITLE1                      1091
#define IDC_LOGO2                       1092
#define IDC_LOGO3                       1093
#define IDC_MODIMAGE                    1093
#define IDC_MOD_IMAGE                   1093
#define IDC_MOD_TEXT                    1095
#define IDC_MOD_SELECT                  1097
#define IDC_MOD_NONE                    1098
#define IDC_MOD_NAME2                   1099
#define IDC_ANISOFILTER_SLIDER          1106
#define IDC_FSAA_SLIDER                 1107
#define IDC_ANISO_SETTING               1108
#define IDC_FSAA_SETTING                1109
#define IDC_CDEPTH_TEXT                 1110
#define IDC_NSVM_TEXT                   1112
#define IDC_OGL_TEXFILTER_LIST          1113
#define IDC_OGL_TEXFILTER_TEXT          1114
#define IDC_SOUND_STATIC                1117
#define IDC_EAX_STATIC                  1119
#define IDC_OAL_WARN_STATIC             1120
#define IDC_CUSTOM_IP_TEXT              1122

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1129
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
