
set(source_files)

add_file_folder("Source"
    src/AssociatedPlainTextDocument.h
    src/CheckedDataListModel.h
    src/FredApplication.cpp
    src/FredApplication.h
    src/fredstubs.cpp
    src/main.cpp
    src/util.cpp
    src/util.h
)

if (WIN32)
    add_file_folder("Source"
        src/qmain.cpp
    )
endif()

add_file_folder("Source/Mission"
    src/mission/Editor.cpp
	src/mission/EditorWing.cpp
    src/mission/Editor.h
    src/mission/EditorViewport.cpp
    src/mission/EditorViewport.h
    src/mission/FredRenderer.cpp
    src/mission/FredRenderer.h
    src/mission/IDialogProvider.h
    src/mission/management.cpp
    src/mission/management.h
	src/mission/missionsave.cpp
	src/mission/missionsave.h
    src/mission/object.cpp
    src/mission/object.h
    src/mission/util.cpp
    src/mission/util.h
)

add_file_folder("Source/Mission/Dialogs"
    src/mission/dialogs/AbstractDialogModel.cpp
    src/mission/dialogs/AbstractDialogModel.h
	src/mission/dialogs/AsteroidEditorDialogModel.cpp
	src/mission/dialogs/AsteroidEditorDialogModel.h
	src/mission/dialogs/BackgroundEditorDialogModel.h
	src/mission/dialogs/BackgroundEditorDialogModel.cpp
	src/mission/dialogs/BriefingEditorDialogModel.cpp
    src/mission/dialogs/BriefingEditorDialogModel.h
	src/mission/dialogs/CampaignEditorDialogModel.cpp
	src/mission/dialogs/CampaignEditorDialogModel.h
	src/mission/dialogs/CommandBriefingDialogModel.cpp
	src/mission/dialogs/CommandBriefingDialogModel.h
	src/mission/dialogs/DebriefingDialogModel.cpp
	src/mission/dialogs/DebriefingDialogModel.h
    src/mission/dialogs/FictionViewerDialogModel.cpp
    src/mission/dialogs/FictionViewerDialogModel.h
	src/mission/dialogs/FormWingDialogModel.cpp
	src/mission/dialogs/FormWingDialogModel.h
	src/mission/dialogs/GlobalShipFlagsDialogModel.cpp
	src/mission/dialogs/GlobalShipFlagsDialogModel.h
	src/mission/dialogs/JumpNodeEditorDialogModel.cpp
	src/mission/dialogs/JumpNodeEditorDialogModel.h
	src/mission/dialogs/MissionCutscenesDialogModel.cpp
	src/mission/dialogs/MissionCutscenesDialogModel.h
	src/mission/dialogs/MissionEventsDialogModel.cpp
	src/mission/dialogs/MissionEventsDialogModel.h
	src/mission/dialogs/MissionGoalsDialogModel.cpp
	src/mission/dialogs/MissionGoalsDialogModel.h
	src/mission/dialogs/MissionSpecDialogModel.cpp
	src/mission/dialogs/MissionSpecDialogModel.h
	src/mission/dialogs/MusicPlayerDialogModel.cpp
	src/mission/dialogs/MusicPlayerDialogModel.h
	src/mission/dialogs/MusicTBLViewerModel.cpp
	src/mission/dialogs/MusicTBLViewerModel.h
	src/mission/dialogs/ObjectOrientEditorDialogModel.cpp
	src/mission/dialogs/ObjectOrientEditorDialogModel.h
	src/mission/dialogs/ReinforcementsEditorDialogModel.cpp	
	src/mission/dialogs/ReinforcementsEditorDialogModel.h
	src/mission/dialogs/RelativeCoordinatesDialogModel.cpp
	src/mission/dialogs/RelativeCoordinatesDialogModel.h
	src/mission/dialogs/SelectionDialogModel.cpp
	src/mission/dialogs/SelectionDialogModel.h
	src/mission/dialogs/ShieldSystemDialogModel.cpp
	src/mission/dialogs/ShieldSystemDialogModel.h
	src/mission/dialogs/TeamLoadoutDialogModel.cpp
	src/mission/dialogs/TeamLoadoutDialogModel.h
	src/mission/dialogs/VariableDialogModel.cpp
	src/mission/dialogs/VariableDialogModel.h
	src/mission/dialogs/VoiceActingManagerModel.h
	src/mission/dialogs/VoiceActingManagerModel.cpp
	src/mission/dialogs/VolumetricNebulaDialogModel.cpp
	src/mission/dialogs/VolumetricNebulaDialogModel.h
	src/mission/dialogs/WaypointEditorDialogModel.cpp
	src/mission/dialogs/WaypointEditorDialogModel.h
	src/mission/dialogs/WingEditorDialogModel.cpp
	src/mission/dialogs/WingEditorDialogModel.h
)
add_file_folder("Source/Mission/Dialogs/MissionSpecs"
	src/mission/dialogs/MissionSpecs/CustomDataDialogModel.cpp
	src/mission/dialogs/MissionSpecs/CustomDataDialogModel.h
	src/mission/dialogs/MissionSpecs/CustomStringsDialogModel.cpp
	src/mission/dialogs/MissionSpecs/CustomStringsDialogModel.h
	src/mission/dialogs/MissionSpecs/CustomWingNamesDialogModel.cpp
	src/mission/dialogs/MissionSpecs/CustomWingNamesDialogModel.h
	src/mission/dialogs/MissionSpecs/SoundEnvironmentDialogModel.cpp
	src/mission/dialogs/MissionSpecs/SoundEnvironmentDialogModel.h
)
add_file_folder("Source/Mission/Dialogs/ShipEditor"
	src/mission/dialogs/ShipEditor/ShipEditorDialogModel.h
	src/mission/dialogs/ShipEditor/ShipEditorDialogModel.cpp
	src/mission/dialogs/ShipEditor/ShipInitialStatusDialogModel.cpp
	src/mission/dialogs/ShipEditor/ShipInitialStatusDialogModel.h
	src/mission/dialogs/ShipEditor/ShipGoalsDialogModel.h
	src/mission/dialogs/ShipEditor/ShipGoalsDialogModel.cpp
	src/mission/dialogs/ShipEditor/ShipFlagsDialogModel.cpp
	src/mission/dialogs/ShipEditor/ShipFlagsDialogModel.h
	src/mission/dialogs/ShipEditor/ShipSpecialStatsDialogModel.h
	src/mission/dialogs/ShipEditor/ShipSpecialStatsDialogModel.cpp
	src/mission/dialogs/ShipEditor/ShipTextureReplacementDialogModel.h
	src/mission/dialogs/ShipEditor/ShipTextureReplacementDialogModel.cpp
	src/mission/dialogs/ShipEditor/ShipTBLViewerModel.cpp
	src/mission/dialogs/ShipEditor/ShipTBLViewerModel.h
	src/mission/dialogs/ShipEditor/ShipWeaponsDialogModel.cpp
	src/mission/dialogs/ShipEditor/ShipWeaponsDialogModel.h
	src/mission/dialogs/ShipEditor/WeaponsTBLViewerModel.cpp
	src/mission/dialogs/ShipEditor/WeaponsTBLViewerModel.h
	src/mission/dialogs/ShipEditor/ShipCustomWarpDialogModel.h
	src/mission/dialogs/ShipEditor/ShipCustomWarpDialogModel.cpp
	src/mission/dialogs/ShipEditor/ShipAltShipClassModel.h
	src/mission/dialogs/ShipEditor/ShipAltShipClassModel.cpp
)

add_file_folder("Source/UI"
    src/ui/FredView.cpp
    src/ui/FredView.h
    src/ui/QtGraphicsOperations.cpp
    src/ui/QtGraphicsOperations.h
)

add_file_folder("Source/UI/Dialogs"
	src/ui/dialogs/AboutDialog.cpp
	src/ui/dialogs/AboutDialog.h
	src/ui/dialogs/AsteroidEditorDialog.cpp
	src/ui/dialogs/AsteroidEditorDialog.h
	src/ui/dialogs/BackgroundEditorDialog.h
	src/ui/dialogs/BackgroundEditorDialog.cpp
    src/ui/dialogs/BriefingEditorDialog.cpp
    src/ui/dialogs/BriefingEditorDialog.h
	src/ui/dialogs/CampaignEditorDialog.h
	src/ui/dialogs/CampaignEditorDialog.cpp
	src/ui/dialogs/CommandBriefingDialog.cpp
	src/ui/dialogs/CommandBriefingDialog.h
	src/ui/dialogs/DebriefingDialog.cpp
	src/ui/dialogs/DebriefingDialog.h
	src/ui/dialogs/FictionViewerDialog.cpp
	src/ui/dialogs/FictionViewerDialog.h
	src/ui/dialogs/FormWingDialog.cpp
	src/ui/dialogs/FormWingDialog.h
	src/ui/dialogs/GlobalShipFlagsDialog.cpp
	src/ui/dialogs/GlobalShipFlagsDialog.h
	src/ui/dialogs/JumpNodeEditorDialog.cpp
	src/ui/dialogs/JumpNodeEditorDialog.h
	src/ui/dialogs/MissionCutscenesDialog.cpp
	src/ui/dialogs/MissionCutscenesDialog.h
	src/ui/dialogs/MissionEventsDialog.cpp
    src/ui/dialogs/MissionEventsDialog.h
	src/ui/dialogs/MissionGoalsDialog.cpp
	src/ui/dialogs/MissionGoalsDialog.h
	src/ui/dialogs/MissionSpecDialog.cpp
	src/ui/dialogs/MissionSpecDialog.h
	src/ui/dialogs/MusicPlayerDialog.cpp
	src/ui/dialogs/MusicPlayerDialog.h
	src/ui/dialogs/MusicTBLViewer.cpp
	src/ui/dialogs/MusicTBLViewer.h
	src/ui/dialogs/ObjectOrientEditorDialog.cpp
	src/ui/dialogs/ObjectOrientEditorDialog.h
	src/ui/dialogs/ReinforcementsEditorDialog.cpp
	src/ui/dialogs/ReinforcementsEditorDialog.h
	src/ui/dialogs/RelativeCoordinatesDialog.cpp
	src/ui/dialogs/RelativeCoordinatesDialog.h
	src/ui/dialogs/SelectionDialog.cpp
	src/ui/dialogs/SelectionDialog.h
	src/ui/dialogs/ShieldSystemDialog.h
	src/ui/dialogs/ShieldSystemDialog.cpp
	src/ui/dialogs/TeamLoadoutDialog.cpp	
	src/ui/dialogs/TeamLoadoutDialog.h
	src/ui/dialogs/VariableDialog.cpp
	src/ui/dialogs/VariableDialog.h
	src/ui/dialogs/VoiceActingManager.h
	src/ui/dialogs/VoiceActingManager.cpp
	src/ui/dialogs/VolumetricNebulaDialog.h
	src/ui/dialogs/VolumetricNebulaDialog.cpp
	src/ui/dialogs/WaypointEditorDialog.cpp
	src/ui/dialogs/WaypointEditorDialog.h
	src/ui/dialogs/WingEditorDialog.cpp
	src/ui/dialogs/WingEditorDialog.h
)
add_file_folder("Source/UI/Dialogs/MissionSpecs"
	src/ui/dialogs/MissionSpecs/CustomDataDialog.cpp
	src/ui/dialogs/MissionSpecs/CustomDataDialog.h
	src/ui/dialogs/MissionSpecs/CustomStringsDialog.cpp
	src/ui/dialogs/MissionSpecs/CustomStringsDialog.h
	src/ui/dialogs/MissionSpecs/CustomWingNamesDialog.cpp
	src/ui/dialogs/MissionSpecs/CustomWingNamesDialog.h
	src/ui/dialogs/MissionSpecs/SoundEnvironmentDialog.cpp
	src/ui/dialogs/MissionSpecs/SoundEnvironmentDialog.h
)
add_file_folder("Source/UI/Dialogs/ShipEditor"
	src/ui/dialogs/ShipEditor/ShipEditorDialog.h
	src/ui/dialogs/ShipEditor/ShipEditorDialog.cpp
	src/ui/dialogs/ShipEditor/ShipInitialStatusDialog.h
	src/ui/dialogs/ShipEditor/ShipInitialStatusDialog.cpp
	src/ui/dialogs/ShipEditor/ShipGoalsDialog.cpp
	src/ui/dialogs/ShipEditor/ShipGoalsDialog.h
	src/ui/dialogs/ShipEditor/ShipFlagsDialog.h
	src/ui/dialogs/ShipEditor/ShipFlagsDialog.cpp
	src/ui/dialogs/ShipEditor/ShipSpecialStatsDialog.cpp
	src/ui/dialogs/ShipEditor/ShipSpecialStatsDialog.h
	src/ui/dialogs/ShipEditor/ShipTextureReplacementDialog.h
	src/ui/dialogs/ShipEditor/ShipTextureReplacementDialog.cpp
	src/ui/dialogs/ShipEditor/ShipTBLViewer.h
	src/ui/dialogs/ShipEditor/ShipTBLViewer.cpp
	src/ui/dialogs/ShipEditor/ShipWeaponsDialog.cpp
	src/ui/dialogs/ShipEditor/ShipWeaponsDialog.h
	src/ui/dialogs/ShipEditor/BankModel.cpp
	src/ui/dialogs/ShipEditor/BankModel.h
	src/ui/dialogs/ShipEditor/ShipCustomWarpDialog.h
	src/ui/dialogs/ShipEditor/ShipCustomWarpDialog.cpp
	src/ui/dialogs/ShipEditor/ShipAltShipClass.h
	src/ui/dialogs/ShipEditor/ShipAltShipClass.cpp
	src/ui/dialogs/ShipEditor/WeaponsTBLViewer.cpp
	src/ui/dialogs/ShipEditor/WeaponsTBLViewer.h
)
add_file_folder("Source/UI/General"
	src/ui/dialogs/General/CheckBoxListDialog.cpp
	src/ui/dialogs/General/CheckBoxListDialog.h
	src/ui/dialogs/General/ImagePickerDialog.cpp
	src/ui/dialogs/General/ImagePickerDialog.h
)

add_file_folder("Source/UI/Util"
	src/ui/util/ImageRenderer.cpp
	src/ui/util/ImageRenderer.h
	src/ui/util/menu.cpp
	src/ui/util/menu.h
	src/ui/util/SignalBlockers.cpp
	src/ui/util/SignalBlockers.h
)

add_file_folder("Source/UI/Widgets"
    src/ui/widgets/CampaignMissionGraph.cpp
	src/ui/widgets/CampaignMissionGraph.h
    src/ui/widgets/ColorComboBox.cpp
    src/ui/widgets/ColorComboBox.h
	src/ui/widgets/LineEditDelegate.cpp
	src/ui/widgets/LineEditDelegate.h
	src/ui/widgets/FlagList.cpp
	src/ui/widgets/FlagList.h
	src/ui/widgets/NoWheelComboBox.cpp
	src/ui/widgets/NoWheelComboBox.h
	src/ui/widgets/NoWheelSpinBox.cpp
	src/ui/widgets/NoWheelSpinBox.h
    src/ui/widgets/renderwidget.cpp
    src/ui/widgets/renderwidget.h
	src/ui/widgets/sexp_tree.cpp
	src/ui/widgets/sexp_tree.h
	src/ui/widgets/ShipFlagCheckbox.h
	src/ui/widgets/ShipFlagCheckbox.cpp
	src/ui/widgets/SimpleListSelectDialog.cpp
	src/ui/widgets/SimpleListSelectDialog.h
	src/ui/widgets/weaponList.cpp
	src/ui/widgets/weaponList.h
	src/ui/widgets/bankTree.cpp
	src/ui/widgets/bankTree.h
	src/ui/widgets/PersonaColorComboBox.cpp
	src/ui/widgets/PersonaColorComboBox.h
)

add_file_folder("UI"
	ui/AboutDialog.ui
	ui/AsteroidEditorDialog.ui
	ui/BackgroundEditor.ui
	ui/BriefingEditorDialog.ui
	ui/CampaignEditorDialog.ui
	ui/CheckBoxListDialog.ui
	ui/CommandBriefingDialog.ui
	ui/CustomDataDialog.ui
	ui/CustomStringsDialog.ui
	ui/CustomWingNamesDialog.ui
	ui/DebriefingDialog.ui
	ui/FictionViewerDialog.ui
	ui/FormWingDialog.ui
    ui/FredView.ui
	ui/GlobalShipFlagsDialog.ui
	ui/JumpNodeEditorDialog.ui
	ui/TeamLoadoutDialog.ui
	ui/MissionCutscenesDialog.ui
	ui/MissionEventsDialog.ui
	ui/MissionGoalsDialog.ui
	ui/MissionSpecDialog.ui
	ui/MusicPlayerDialog.ui
	ui/ObjectOrientationDialog.ui
	ui/ReinforcementsDialog.ui
	ui/RelativeCoordinatesDialog.ui
	ui/SelectionDialog.ui
	ui/ShieldSystemDialog.ui
	ui/SoundEnvironmentDialog.ui
	ui/VoiceActingManager.ui
	ui/VolumetricNebulaDialog.ui
    ui/WaypointEditorDialog.ui
	ui/ShipEditorDialog.ui
	ui/ShipInitialStatus.ui
	ui/ShipGoalsDialog.ui
	ui/ShipSpecialStatsDialog.ui
	ui/ShipFlagsDialog.ui
	ui/ShipTextureReplacementDialog.ui
	ui/ShipTBLViewer.ui
	ui/ShipCustomWarpDialog.ui
	ui/ShipAltShipClass.ui
	ui/ShipWeaponsDialog.ui
	ui/VariableDialog.ui
	ui/WingEditorDialog.ui
)

add_file_folder("Resources"
    resources/resources.qrc
)

if (WIN32)
    add_file_folder("Resources/Windows"
        resources/win/qtfred.manifest
        resources/win/qtfred.rc
    )
endif()

add_file_folder("Resources/Images"
	resources/images/arrow_down.png
	resources/images/arrow_left.png
	resources/images/arrow_right.png
	resources/images/arrow_up.png
    resources/images/bitmap1.png
    resources/images/black_do.png
    resources/images/bmp00001.png
    resources/images/chained_directive.png
    resources/images/chained.png
    resources/images/constx.png
    resources/images/constxy.png
    resources/images/constxz.png
    resources/images/consty.png
    resources/images/constyz.png
    resources/images/constz.png
    resources/images/cursor_rotate.png
    resources/images/data00.png
    resources/images/data05.png
    resources/images/data10.png
    resources/images/data15.png
    resources/images/data20.png
    resources/images/data25.png
    resources/images/data30.png
    resources/images/data35.png
    resources/images/data40.png
    resources/images/data45.png
    resources/images/data50.png
    resources/images/data55.png
    resources/images/data60.png
    resources/images/data65.png
    resources/images/data70.png
    resources/images/data75.png
    resources/images/data80.png
    resources/images/data85.png
    resources/images/data90.png
    resources/images/data95.png
    resources/images/data.png
    resources/images/fred_app.png
    resources/images/fred_debug.png
    resources/images/freddoc.ico
    resources/images/fred.ico
    resources/images/fredknows.png
    resources/images/fred_splash.png
    resources/images/green_do.png
	resources/images/next.png
    resources/images/orbitsel.png
    resources/images/play.png
	resources/images/prev.png
    resources/images/root_directive.png
    resources/images/root.png
    resources/images/rotlocal.png
    resources/images/selectlist.png
    resources/images/selectlock.png
    resources/images/selectmove.png
    resources/images/select.png
    resources/images/selectrot.png
    resources/images/showdist.png
    resources/images/splash.png
	resources/images/stop.png
    resources/images/toolbar1.png
    resources/images/toolbar.png
    resources/images/V_fred.ico
    resources/images/variable.png
    resources/images/wingdisband.png
    resources/images/wingform.png
    resources/images/zoomext.png
    resources/images/zoomsel.png
)
