name: Publish Standalone docker image

on:
  push:
    tags:
    - 'nightly_*'
    - 'release_*'

jobs:
  build_images:
    if: github.repository == 'scp-fs2open/fs2open.github.com'
    strategy:
      matrix:
        configuration: [FastDebug, Release]
        include:
        - configuration: FastDebug
          tag_suffix: -debug
        - configuration: Release
          tag_suffix: ""
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Add curl to the container
      run: |    
        apt-get update -y
        apt -y install curl jq
    - uses: actions/checkout@v1
      name: Checkout
      with:
        submodules: true
    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.204.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/scp-fs2open/standalone_server
        tag-latest: false

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/standalone/Dockerfile
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}${{ matrix.tag_suffix }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        build-args: |
          build_type=${{ matrix.configuration }}
