name: Publish Standalone docker image

on:
  push:
    tags:
    - '*'

jobs:
  build_images:
    strategy:
      matrix:
        configuration: [FastDebug, Release]
        include:
        - configuration: FastDebug
          latest_tag: latest_debug
          nightly_tag: nightly_debug
          release_tag: release_debug
        - configuration: Release
          latest_tag: latest
          nightly_tag: nightly
          release_tag: release
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout
      with:
        submodules: true
    - name: Docker login
      run: echo ${{ secrets.DOCKER_ACCESSTOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Docker build
      run: docker build --build-arg build_type=${{ matrix.configuration }} -f docker/standalone/Dockerfile -t ${{ secrets.DOCKER_REPOSITORY }}:${{ matrix.latest_tag }} .

    - name: Push latest tag
      run: |
        docker push ${{ secrets.DOCKER_REPOSITORY }}:${{ matrix.latest_tag }}

    - name: Push nightly tag
      if: contains(github.ref, 'refs/tags/nightly_')
      run: |
        docker tag ${{ secrets.DOCKER_REPOSITORY }}:${{ matrix.latest_tag }} ${{ secrets.DOCKER_REPOSITORY }}:${{ matrix.nightly_tag }}
        docker push ${{ secrets.DOCKER_REPOSITORY }}:${{ matrix.nightly_tag }}

    - name: Push release tag
      if: contains(github.ref, 'refs/tags/release_')
      run: |
        docker tag ${{ secrets.DOCKER_REPOSITORY }}:${{ matrix.latest_tag }} ${{ secrets.DOCKER_REPOSITORY }}:${{ matrix.release_tag }}
        docker push ${{ secrets.DOCKER_REPOSITORY }}:${{ matrix.release_tag }}
