/*
 * Created by Ian "Goober5000" Warfield for the Freespace2 Source Code Project.
 * You may not sell or otherwise commercially exploit the source or things you
 * create based on the source.
 *
 */ 

/*
 * $Logfile: /Freespace2/code/wxFRED2/wxFREDXRC.cpp $
 * $Revision: 1.1 $
 * $Date: 2005-04-24 14:42:27 $
 * $Author: Goober5000 $
 *
 * New cross-platform version of FRED2
 *
 * $Log: not supported by cvs2svn $
 * Revision 1.0  2005/04/24 08:41:00  Goober5000
 * Addition to CVS repository
 *
 */

// This file just exists to compile the autogenerated XRC stuff.
#include "wxfred_xrc.h"
#include "wxfred_xrc.inl"